name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: linux-x64
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
        cache: true

    - name: Build
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        release_name="App-$tag"

        # Build everything
        dotnet publish server/TransferRoom.Api/TransferRoom.Api.csproj -c Release -o "$release_name"

        # Pack files
        tar czvf "${release_name}.tar.gz" "$release_name"

        # Delete output directory
        rm -r "$release_name"

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "App*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
