name: Azure Static Web Apps CI/CD

on: workflow_dispatch

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: client
      AZURE_WEBAPP_NAME: transfer-room-client
      NODE_VERSION: '18.x'
      VITE_API_URL: "https://transfer-room-service.azurewebsites.net"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false

    - name: Build And Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_SEA_0EA800E03 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./client"
        output_location: "dist"
