name: Deploy application to azure

on: workflow_dispatch

jobs:
  publish-server:
    name: Deploy server
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: transfer-room-service
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"
      APPLICATION_PATH: "server/TransferRoom.Api/TransferRoom.Api.sln"
      DOTNET_VERSION: '8.x'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET 📦
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Restore dependencies 📂
      run: dotnet restore ${{env.APPLICATION_PATH}}

    - name: Build 🧱
      run: dotnet build ${{env.APPLICATION_PATH}} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{env.APPLICATION_PATH}} --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

  publish-client:
    name: Deploy web client
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: client
      AZURE_WEBAPP_NAME: transfer-room-client
      NODE_VERSION: '18.x'
      VITE_API_URL: "https://transfer-room-service.azurewebsites.net"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false

    - name: Build And Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_SEA_0EA800E03 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./client"
        output_location: "dist"
